name: Sync Labels

on:
  push:
    branches:
      - main

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: labels.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
